version: 2

before:
  hooks:
    # may remove this if you don't use go modules.
    - go mod tidy

builds:
  - binary: test
    main: ./cmd/api/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers_v2:
  - id: default
    dockerfile: Dockerfile
    ids: 
      - test
    images:
      - ghcr.io/aLieexe/{{ .ProjectName }}
    tags:
      - latest
      - "{{ .Tag }}"
    # This is already the default but, whatever
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "Chat will this work?? Or nah??"
      "org.opencontainers.image.url": "https://github.com/aLieexe/{{ .ProjectName }}"
      "org.opencontainers.image.source": "https://github.com/aLieexe/{{ .ProjectName }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.licenses": "MIT"
    retry:
      attempts: 3
      delay: 10s

# https://github.com/goreleaser/example-supply-chain/blob/main/.goreleaser.yaml
# https://github.com/goreleaser/example-secure/blob/main/.goreleaser.yaml
sboms:
  - artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

docker_signs:
  - cmd: cosign
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"


archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{- .ProjectName }}_ {{- .Version }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end -}}
    
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      # - completions/*

changelog:
  sort: asc
  filters:
    include:
      - '^feat:'
      - '^fix:'
      - '^chore:'
      - '^refactor:'
      - '^perf:'
      - '^build:'

checksum:
  name_template: "checksums.txt"