name: continous integration
on:
  push:
    branches: 
      - main
      - fix/*
      - feat/*
  pull_request:
    branches:
      - main


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.x'
      
      - name: Display Go version
        run: go version

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          # The path to cache is the Go module cache directory
          path: ~/go/pkg/mod
          # The key is unique to the OS and the contents of go.sum
          # If go.sum changes, the key changes, and a new cache is created.
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          # A fallback key to use the most recent cache if the exact key isn't found
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=5m


